### ISSUE TITLE
The metadata tactic needs de-duplication

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#186] opened 2016-04-18 20:56 UTC
I built a charm from several layers and I see all the maintainers are in the resulting `metadata.yaml` file. Some of this is our fault, we spelled our names or emails differently, but the names that are exactly the same should be de-duplicated.

```yaml
"name": "kubernetes"
"summary": "Kubernetes is an application container orchestration platform."
"description": |
  Kubernetes is an open-source platform for deplying, scaling, and operations
  of appliation containers across a cluster of hosts. Kubernetes is portable
  in that it works with public, private, and hybrid clouds. Extensible through
  a pluggable infrastructure. Self healing in that it will automatically
  restart and place containers on healthy nodes if a node ever goes away.
"tags":
- "containers"
- "layer"
- "containers"
- "networking"
- "infrastructure"
- "security"
- "infrastructure"
"requires":
  "etcd":
    "interface": "etcd"
"provides":
  "dockerhost":
    "interface": "dockerhost"
    "scope": "container"
"peers":
  "certificates":
    "interface": "tls"
"maintainers":
- "Charles Butler <charles.butler@canonical.com>"
- "Matt Bruzek <matthew.bruzek@canonical.com>"
- "Charles Butler <charles.butler@canonical.com>"
- "Matthew Bruzek <matthew.bruzek@ubuntu.com>"
- "Matthew Bruzek <matthew.bruzek@canonical.com>"
- "Charles Butler <charles.butler@canonical.com>"
"subordinate": !!bool "false"
```
The **maintainer** and the **tags** values could be de-duplicated. This could be done by casting them to a set or using a loop to detect if a value has already been written by another method.

**Comment by marcoceppi** [comment] 2016-04-18 23:33
The problem is, maintainers and tags are lists not sets. This could be easily addressed by converting those two fields in the metadata tactics

**Comment by johnsca** [comment] 2016-04-19 18:50
I feel like `maintainer` is a case where merging the lists doesn't make sense, and only the charm's `maintainer` should apply.

**Comment by chuckbutler** [comment] 2016-05-18 16:24
I agree with @johnsca here on this. The top most layer is and should define the actual maintainer.  Just because I had a hand in layer-tls (as an example), doesn't mean I want or have the bandwidth to lend to support the consuming layer(s) that may be using the layer improperly. So attaching my name to the resulting charm is kind of a bad thing to do. 

We'll see layer authors who are putting extra metadata (who knows why, maybe this is for testing with amulet so the layer is standalone) in their layers start to propagate all over the store and own things they had no intention in owning.

This will be a legitimate problem as the charm store ages, contributors come/go, and we have a slew of charms that have become unmaintained (See: series:precise as an example)

**Comment by mbruzek** [comment] 2016-05-18 17:39
I am not sure @johnsca and @chuckbutler are correct on this one. If there are maintainers in intermediate layers they may want some kind of credit or acknowledgement that the charm was built using their layer or work. I would not exclude them by default but we could make that a flag or an option.

**Comment by stub42** [comment] 2016-05-20 06:11
Maintainership is a responsibility, so I certainly wouldn't overload that by using it to assign credit. If you want credit or acknowledgement, add some new metadata with that meaning.

**Closed** 2016-06-29 13:16 UTC
Labels: charm-build
