### ISSUE TITLE
charm build on yaml needs to do proper type casting

### ISSUE THREAD

**Issue by marcoceppi** [juju/charm-tools#99] opened 2016-02-03 20:11 UTC
When you have a `config.yaml` with the following:

```yaml
options:
  install_keys:
    type: string
    description: The key for the Debian package repository.
    default: "01182252"
```

Because this is actually a string but /may/ be a string of INTs Yaml parses this to an integer, writes the built YAML as:

```yaml
options:
  install_keys:
    type: string
    description: The key for the Debian package repository.
    default: 01182252
```

When writing the YAML back out, charm build should typecast based on `type` of the config options (string, int, bool)

To test, check out @srbaker [neo4j layer](https://github.com/srbaker/neo4j-charm)

**Comment by johnsca** [comment] 2016-02-04 14:40
It seems to be an issue in pyyaml, and is due to the leading zero.

**Comment by mbruzek** [comment] 2016-02-04 14:51
Actually @johnsca it looks like the tactics.py class imports ruamel to preserve the comments on a round trip. I think we need to focus on options we can pas ruamel or fix this problem there.

**Comment by mbruzek** [comment] 2016-02-05 15:47
This problem is due to the ruamel library that is use in the charm build python classes. After installing the latest version of ruamel (0.10.20), I can still reproduce this bug with strings that start with zero and are over nine characters in length.  

I created a bug against ruamel for this problem: https://bitbucket.org/ruamel/yaml/issues/23/strings-with-leading-zeros-are-round

Here is the sample code that reproduces this bug.
```python
#!/usr/bin/env python

from ruamel import yaml

yaml_string = """\
options:
  key: "{0}"
"""
value = ""
for x in range(0,12): 
    value = value + str(x)
    string = yaml_string.format(value)
    data = yaml.load(string, Loader=yaml.RoundTripLoader)
    print(yaml.dump(data, Dumper=yaml.RoundTripDumper))
```

**Comment by stub42** [comment] 2016-02-06 07:03
Accoding to upstream, the unquoted 01182252 is still a string. Its not a decimal because it starts with '0'. Its not an octal number because it contains an 8. So it falls back to being a string, and no quotes are needed.

pyyaml agrees with this:
```python
>>> type(yaml.safe_load("'09876534'"))
<type 'str'>
>>> type(yaml.safe_load("09876534"))
<type 'str'>
>>> type(yaml.safe_load("076534"))
<type 'int'>
```

**Comment by marcoceppi** [comment] 2016-02-06 08:11
Then this is a bug in go-yaml parsing

**Comment by mbruzek** [comment] 2016-02-09 17:38
@srbaker This charm-tools patch works around your problem, but I have traced the root back to the go-yaml implementation and opened an issue https://github.com/go-yaml/yaml/issues/157

**Comment by mbruzek** [comment] 2016-02-09 20:49
We should close this issue because it is not problem with charm-tools. The ruamel yaml package is handling the round trip correctly and by the book. PR #104 introduces a workaround that quotes all strings with double quotes. There is an issue open against the Go lang implementation that Juju uses and an open bug against Juju itself.

**Comment by marcoceppi** [comment] 2016-02-09 21:00
I will close this once we do a patch release for charm-tools. I'm waiting
atm as there are a few more patches I want to land.

**Comment by galgalesh** [comment] 2016-03-03 15:56
Any idea when the patch will land?

**Comment by marcoceppi** [comment] 2016-03-03 17:10
It's in alpha1 in ppa:marcoceppi/charm-tools-2.0 we will cherry pick this
for a 1.11.2 release

Marco

**Closed** 2016-03-21 19:54 UTC
Labels: charm-layers
